todotoo/config/routes.rb
Rails.application.routes.draw do
  resources :todoitems
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

todotoo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

todotoo/app/models/todoitem.rb
class Todoitem < ApplicationRecord
end

todotoo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

todotoo/app/controllers/todoitems_controller.rb
class TodoitemsController < ApplicationController
  before_action :set_todoitem, only: [:show, :edit, :update, :destroy]

  # GET /todoitems
  # GET /todoitems.json
  def index
    @todoitems = Todoitem.all
  end

  # GET /todoitems/1
  # GET /todoitems/1.json
  def show
  end

  # GET /todoitems/new
  def new
    @todoitem = Todoitem.new
  end

  # GET /todoitems/1/edit
  def edit
  end

  # POST /todoitems
  # POST /todoitems.json
  def create
    @todoitem = Todoitem.new(todoitem_params)

    respond_to do |format|
      if @todoitem.save
        format.html { redirect_to @todoitem, notice: 'Todoitem was successfully created.' }
        format.json { render :show, status: :created, location: @todoitem }
      else
        format.html { render :new }
        format.json { render json: @todoitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todoitems/1
  # PATCH/PUT /todoitems/1.json
  def update
    respond_to do |format|
      if @todoitem.update(todoitem_params)
        format.html { redirect_to @todoitem, notice: 'Todoitem was successfully updated.' }
        format.json { render :show, status: :ok, location: @todoitem }
      else
        format.html { render :edit }
        format.json { render json: @todoitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todoitems/1
  # DELETE /todoitems/1.json
  def destroy
    @todoitem.destroy
    respond_to do |format|
      format.html { redirect_to todoitems_url, notice: 'Todoitem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todoitem
      @todoitem = Todoitem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todoitem_params
      params.require(:todoitem).permit(:description, :duedate)
    end
end

todotoo/app/helpers/application_helper.rb
module ApplicationHelper
end

todotoo/app/helpers/todoitems_helper.rb
module TodoitemsHelper
end

todotoo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todotoo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

todotoo/app/views/todoitems/_form.html.erb
<%= form_for(todoitem) do |f| %>
  <% if todoitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todoitem.errors.count, "error") %> prohibited this todoitem from being saved:</h2>

      <ul>
      <% todoitem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :duedate %>
    <%= f.datetime_select :duedate %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

todotoo/app/views/todoitems/edit.html.erb
<h1>Editing Todoitem</h1>

<%= render 'form', todoitem: @todoitem %>

<%= link_to 'Show', @todoitem %> |
<%= link_to 'Back', todoitems_path %>

todotoo/app/views/todoitems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todoitems</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Duedate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todoitems.each do |todoitem| %>
      <tr>
        <td><%= todoitem.description %></td>
        <td><%= todoitem.duedate %></td>
        <td><%= link_to 'Show', todoitem %></td>
        <td><%= link_to 'Edit', edit_todoitem_path(todoitem) %></td>
        <td><%= link_to 'Destroy', todoitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todoitem', new_todoitem_path %>

todotoo/app/views/todoitems/new.html.erb
<h1>New Todoitem</h1>

<%= render 'form', todoitem: @todoitem %>

<%= link_to 'Back', todoitems_path %>

todotoo/app/views/todoitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @todoitem.description %>
</p>

<p>
  <strong>Duedate:</strong>
  <%= @todoitem.duedate %>
</p>

<%= link_to 'Edit', edit_todoitem_path(@todoitem) %> |
<%= link_to 'Back', todoitems_path %>